traffic_control/mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('req1', mainapp.req1, name='req1'),
    path('req2', mainapp.req2, name='req2'),
    path('req3', mainapp.req3, name='req3'),
    path('req4', mainapp.req4, name='req4'),
    path('req5', mainapp.req5, name='req5'),
    path('req6', mainapp.req6, name='req6'),
    path('req7', mainapp.req7, name='req7'),
    path('req8', mainapp.req8, name='req8'),
    path('req9', mainapp.req9, name='req9'),
    path('req10', mainapp.req10, name='req10'),
]

traffic_control/traffic_control/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('mainapp.urls', namespace='mainapp')),
    path('admin/', admin.site.urls),
]

traffic_control/mainapp/models.py
from django.db import models

# Create your models here.

traffic_control/mainapp/views.py
import requests
from django.shortcuts import render
import json

# https://api.via-dolorosa.ru/rc/1/full_info
from requests import HTTPError


def index(request):
    context = {
        'title': 'главная',
    }
    return render(request, 'mainapp/index.html', context)


def req1(request):
    try:
        response = requests.get('https://api.via-dolorosa.ru/rc/90451/status')
        response_full = requests.get('https://api.via-dolorosa.ru/rc/90451/full_info')
        if response.status_code == 200:
            response.raise_for_status()
            jsons = response.json()
            phase_id = jsons['current_phase_id']
            # print(phase_id)
            s1 = []
            # if phase_id == 1:
            if phase_id == 1:
                s1 = [{
                    "id": 1,
                    "t_osn": 32,
                    "t_prom": 6,
                    "t_min": 4,
                    "is_hidden": False,
                    "directions": [
                        1,
                        2
                    ]}]
            elif phase_id == 2:
                s1 = [{
                    "id": 2,
                    "t_osn": 25,
                    "t_prom": 6,
                    "t_min": 4,
                    "is_hidden": False,
                    "directions": [
                        3
                    ]
                }]
            elif phase_id == 3:
                s1 = [{
                    "id": 3,
                    "t_osn": 15,
                    "t_prom": 6,
                    "t_min": 15,
                    "is_hidden": False,
                    "directions": [
                        4,
                        5,
                        6
                    ]
                }]
            else:
                print('Error')
            if response_full.status_code == 200:
                response_full.raise_for_status()
                jsons_full = response_full.json()
            else:
                jsons_full = 'Ошибка на сервере 500/502'
        else:
            jsons_full = 'Ошибка на сервере статус 500/502'
            jsons = 'Ошибка на сервере 500/502'
            s1 = []
    except Exception:
        print('NO')

    context = {
        'title': 'req1',
        # 'text': text,
        'jsons_full': jsons_full,
        'json': jsons,
        's1': s1,

    }
    return render(request, 'mainapp/req1.html', context)


def req2(request):
    try:
        response = requests.get('https://api.via-dolorosa.ru/rc/90452/status')
        response_full = requests.get('https://api.via-dolorosa.ru/rc/90452/full_info')
        if response.status_code == 200:
            response.raise_for_status()
            jsons = response.json()
            phase_id = jsons['current_phase_id']
            # print(phase_id)
            s1 = []
            # if phase_id == 1:
            if phase_id == 1:
                s1 = [{
                    "id": 1,
                    "t_osn": 32,
                    "t_prom": 6,
                    "t_min": 4,
                    "is_hidden": False,
                    "directions": [
                        1,
                        2
                    ]}]
            elif phase_id == 2:
                s1 = [{
                    "id": 2,
                    "t_osn": 25,
                    "t_prom": 6,
                    "t_min": 4,
                    "is_hidden": False,
                    "directions": [
                        3
                    ]
                }]
            elif phase_id == 3:
                s1 = [{
                    "id": 3,
                    "t_osn": 15,
                    "t_prom": 6,
                    "t_min": 15,
                    "is_hidden": False,
                    "directions": [
                        4,
                        5,
                        6
                    ]
                }]
            else:
                print('Error')
            if response_full.status_code == 200:
                response_full.raise_for_status()
                jsons_full = response_full.json()
            else:
                jsons_full = 'Ошибка на сервере 500/502'
        else:
            jsons_full = 'Ошибка на сервере статус 500/502'
            jsons = 'Ошибка на сервере 500/502'
            s1 = []
    except Exception:
        print('NO')

    context = {
        'title': 'req1',
        # 'text': text,
        'jsons_full': jsons_full,
        'json': jsons,
        's1': s1,

    }
    return render(request, 'mainapp/req2.html', context)


def req3(request):
    try:
        response = requests.get('https://api.via-dolorosa.ru/rc/90453/status')
        response_full = requests.get('https://api.via-dolorosa.ru/rc/90453/full_info')
        if response.status_code == 200:
            response.raise_for_status()
            jsons = response.json()
            phase_id = jsons['current_phase_id']
            # print(phase_id)
            s1 = []
            # if phase_id == 1:
            if phase_id == 1:
                s1 = [{
                    "id": 1,
                    "t_osn": 32,
                    "t_prom": 6,
                    "t_min": 4,
                    "is_hidden": False,
                    "directions": [
                        1,
                        2
                    ]}]
            elif phase_id == 2:
                s1 = [{
                    "id": 2,
                    "t_osn": 25,
                    "t_prom": 6,
                    "t_min": 4,
                    "is_hidden": False,
                    "directions": [
                        3
                    ]
                }]
            elif phase_id == 3:
                s1 = [{
                    "id": 3,
                    "t_osn": 15,
                    "t_prom": 6,
                    "t_min": 15,
                    "is_hidden": False,
                    "directions": [
                        4,
                        5,
                        6
                    ]
                }]
            else:
                print('Error')
            if response_full.status_code == 200:
                response_full.raise_for_status()
                jsons_full = response_full.json()
            else:
                jsons_full = 'Ошибка на сервере 500/502'
        else:
            jsons_full = 'Ошибка на сервере статус 500/502'
            jsons = 'Ошибка на сервере 500/502'
            s1 = []
    except Exception:
        print('NO')

    context = {
        'title': 'req1',
        # 'text': text,
        'jsons_full': jsons_full,
        'json': jsons,
        's1': s1,

    }
    return render(request, 'mainapp/req3.html', context)


def req4(request):
    try:
        response = requests.get('https://api.via-dolorosa.ru/rc/90454/status')
        response_full = requests.get('https://api.via-dolorosa.ru/rc/90454/full_info')
        if response.status_code == 200:
            response.raise_for_status()
            jsons = response.json()
            phase_id = jsons['current_phase_id']
            # print(phase_id)
            s1 = []
            # if phase_id == 1:
            if phase_id == 1:
                s1 = [{
                    "id": 1,
                    "t_osn": 32,
                    "t_prom": 6,
                    "t_min": 4,
                    "is_hidden": False,
                    "directions": [
                        1,
                        2
                    ]}]
            elif phase_id == 2:
                s1 = [{
                    "id": 2,
                    "t_osn": 25,
                    "t_prom": 6,
                    "t_min": 4,
                    "is_hidden": False,
                    "directions": [
                        3
                    ]
                }]
            elif phase_id == 3:
                s1 = [{
                    "id": 3,
                    "t_osn": 15,
                    "t_prom": 6,
                    "t_min": 15,
                    "is_hidden": False,
                    "directions": [
                        4,
                        5,
                        6
                    ]
                }]
            else:
                print('Error')
            if response_full.status_code == 200:
                response_full.raise_for_status()
                jsons_full = response_full.json()
            else:
                jsons_full = 'Ошибка на сервере 500/502'
        else:
            jsons_full = 'Ошибка на сервере статус 500/502'
            jsons = 'Ошибка на сервере 500/502'
            s1 = []
    except Exception:
        print('NO')

    context = {
        'title': 'req1',
        # 'text': text,
        'jsons_full': jsons_full,
        'json': jsons,
        's1': s1,

    }
    return render(request, 'mainapp/req4.html', context)


def req5(request):
    try:
        response = requests.get('https://api.via-dolorosa.ru/rc/90455/status')
        response_full = requests.get('https://api.via-dolorosa.ru/rc/90455/full_info')
        if response.status_code == 200:
            response.raise_for_status()
            jsons = response.json()
            phase_id = jsons['current_phase_id']
            # print(phase_id)
            s1 = []
            # if phase_id == 1:
            if phase_id == 1:
                s1 = [{
                    "id": 1,
                    "t_osn": 32,
                    "t_prom": 6,
                    "t_min": 4,
                    "is_hidden": False,
                    "directions": [
                        1,
                        2
                    ]}]
            elif phase_id == 2:
                s1 = [{
                    "id": 2,
                    "t_osn": 25,
                    "t_prom": 6,
                    "t_min": 4,
                    "is_hidden": False,
                    "directions": [
                        3
                    ]
                }]
            elif phase_id == 3:

traffic_control/mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">

    {#    <meta http-equiv="Refresh" content="5"/>#}

    <title>{{ title|capfirst }}</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Nunito&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
<header class="d-flex justify-content-center py-3">
    <ul class="nav nav-pills">
        <li class="nav-item"><a href="{% url 'mainapp:index' %}" class="nav-link" aria-current="page">Главная</a>
        </li>
        <li class="nav-item"><a href="{% url 'mainapp:req1' %}" class="nav-link" aria-current="page">90451</a>
        <li class="nav-item"><a href="{% url 'mainapp:req2' %}" class="nav-link" aria-current="page">90452</a>
        <li class="nav-item"><a href="{% url 'mainapp:req3' %}" class="nav-link" aria-current="page">90453</a>
        <li class="nav-item"><a href="{% url 'mainapp:req4' %}" class="nav-link" aria-current="page">90454</a>
        <li class="nav-item"><a href="{% url 'mainapp:req5' %}" class="nav-link" aria-current="page">90455</a>
        <li class="nav-item"><a href="{% url 'mainapp:req6' %}" class="nav-link" aria-current="page">90456</a>
        <li class="nav-item"><a href="{% url 'mainapp:req7' %}" class="nav-link" aria-current="page">90457</a>
        <li class="nav-item"><a href="{% url 'mainapp:req8' %}" class="nav-link" aria-current="page">90458</a>
        <li class="nav-item"><a href="{% url 'mainapp:req9' %}" class="nav-link" aria-current="page">90459</a>
        <li class="nav-item"><a href="{% url 'mainapp:req10' %}" class="nav-link" aria-current="page">90460</a>
    </ul>
    </ul>

</header>
<div class="container">
    {% block content %}

    {% endblock %}
</div>

<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
        crossorigin="anonymous"></script>
<script>
    $(".status_90451").click(function () {
        let xhttp = new XMLHttpRequest();
        xhttp.onreadystatechange = function () {
            if (this.readyState === 4 && this.status === 200) {
                document.getElementById("send_status_90451").innerHTML = this.responseText;
            }
        };
        xhttp.open("GET", "https://api.via-dolorosa.ru/rc/90451/status", true);
        xhttp.send();
    });
    setTimeout(function () {
        location.reload();
    }, 5000);
    /*
        setInterval(function () {
            let xhttp = new XMLHttpRequest();
            xhttp.onreadystatechange = function () {
                if (this.readyState === 4 && this.status === 200) {
                    document.getElementById("full_info_90452").innerHTML = this.responseText;
                }
            };
            xhttp.open("GET", "https://api.via-dolorosa.ru/rc/90452/full_info", true);
            xhttp.send();
        }, 2500);
        setInterval(function () {
            let xhttp = new XMLHttpRequest();
            xhttp.onreadystatechange = function () {
                if (this.readyState === 4 && this.status === 200) {
                    document.getElementById("full_info_90453").innerHTML = this.responseText;
                }
            };
            xhttp.open("GET", "https://api.via-dolorosa.ru/rc/90453/full_info", true);
            xhttp.send();
        }, 2500);
        setInterval(function () {
            let xhttp = new XMLHttpRequest();
            xhttp.onreadystatechange = function () {
                if (this.readyState === 4 && this.status === 200) {
                    document.getElementById("full_info_90454").innerHTML = this.responseText;
                }
            };
            xhttp.open("GET", "https://api.via-dolorosa.ru/rc/90454/full_info", true);
            xhttp.send();
        }, 2500);
        setInterval(function () {
            let xhttp = new XMLHttpRequest();
            xhttp.onreadystatechange = function () {
                if (this.readyState === 4 && this.status === 200) {
                    document.getElementById("full_info_90455").innerHTML = this.responseText;
                }
            };
            xhttp.open("GET", "https://api.via-dolorosa.ru/rc/90455/full_info", true);
            xhttp.send();
        }, 2500);
        setInterval(function () {
            let xhttp = new XMLHttpRequest();
            xhttp.onreadystatechange = function () {
                if (this.readyState === 4 && this.status === 200) {
                    document.getElementById("full_info_90456").innerHTML = this.responseText;
                }
            };
            xhttp.open("GET", "https://api.via-dolorosa.ru/rc/90456/full_info", true);
            xhttp.send();
        }, 2500);
        setInterval(function () {
            let xhttp = new XMLHttpRequest();
            xhttp.onreadystatechange = function () {
                if (this.readyState === 4 && this.status === 200) {
                    document.getElementById("full_info_90457").innerHTML = this.responseText;
                }
            };
            xhttp.open("GET", "https://api.via-dolorosa.ru/rc/90457/full_info", true);
            xhttp.send();
        }, 2500);
        setInterval(function () {
            let xhttp = new XMLHttpRequest();
            xhttp.onreadystatechange = function () {
                if (this.readyState === 4 && this.status === 200) {
                    document.getElementById("full_info_90458").innerHTML = this.responseText;
                }
            };
            xhttp.open("GET", "https://api.via-dolorosa.ru/rc/90458/full_info", true);
            xhttp.send();
        }, 2500);

        setInterval(function () {
            let xhttp = new XMLHttpRequest();
            xhttp.onreadystatechange = function () {
                if (this.readyState === 4 && this.status === 200) {
                    document.getElementById("full_info_90459").innerHTML = this.responseText;
                }
            };
            xhttp.open("GET", "https://api.via-dolorosa.ru/rc/90459/full_info", true);
            xhttp.send();
        }, 2500);
        setInterval(function () {
            let xhttp = new XMLHttpRequest();
            xhttp.onreadystatechange = function () {
                if (this.readyState === 4 && this.status === 200) {
                    document.getElementById("full_info_90460").innerHTML = this.responseText;
                }
            };
            xhttp.open("GET", "https://api.via-dolorosa.ru/rc/90460/full_info", true);
            xhttp.send();
        }, 2500);*/
</script>
</body>
</html>

traffic_control/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% block content %}
    {#    <p>URL :{{ response }}</p>#}
    {#    <p id="full_info_90451">JSON : name: {{ json }}</p>#}

{#    <div class="d-grid gap-2">#}
{#        <button class="btn btn-primary status_90451" type="button">Статус</button>#}
{#        <button class="btn btn-success full_info_90451" type="button">Полная информация</button>#}
{#    </div>#}
{% endblock %}

traffic_control/mainapp/templates/mainapp/req1.html
{% extends 'mainapp/base.html' %}
{% block content %}
    <h1>90451</h1>
    <div class="d-grid gap-2">
        <div class="row">
            <div class="col">
                <h3>Полная информация</h3>
                {% if jsons_full.time %}
                    <p>Time: {{ jsons_full.time }}</p>
                    <p>ID: {{ jsons_full.id }}</p>
                    <p>Created_AT: {{ jsons_full.rc_created_at }}</p>
                    <p>Updated_AT: {{ jsons_full.rc_updated_at }}</p>
                    <p>NUM_TL: {{ jsons_full.num_tl }}</p>
                    <p>is_Enabled: {{ jsons_full.is_enabled }}</p>
                    <p>is_Alarmed: {{ jsons_full.is_alarmed }}</p>
                    <p>type: {{ jsons_full.type }}</p>
                    <p>Protocol{{ jsons_full.protocol }}</p>
                    <p>CONN_STATUS: {{ jsons_full.conn_status }}</p>
                    <p>MODE: {{ jsons_full.mode }}</p>
                    <p>PROGRAM_ID:{{ jsons_full.program_id }}</p>
                    <p>KEEP_PHASE_ID: {{ jsons_full.keep_phase_id }}</p>
                    <p>Changed_time_at: {{ jsons_full.changed_time_at }}</p>
                    <p>Real_mode: {{ jsons_full.real_mode }}</p>
                    <p>Real_program_ID: {{ jsons_full.real_program_id }}</p>
                    <p>Real_keep_phase_id: {{ jsons_full.real_keep_phase_id }}</p>
                    <p>Program_created_at: {{ jsons_full.program_created_at }}</p>
                    <p>Program_updated_at{{ jsons_full.program_updated_at }}</p>
                    <p>T-Cycle: {{ jsons_full.t_cycle }}</p>
                    <p>Program_Type: {{ jsons_full.program_type }}</p>
                    <p>Start_phase_id: {{ jsons_full.start_phase_id }}</p>
                {% else %}
                    <p>Ошибка на сервере 500/502</p>
                {% endif %}
            </div>
            <div class="col">
                <h3>Статус</h3>
                {% if json %}
                    <p>{{ json }}</p>
                {% else %}
                    <p>Ошибка на сервере 500/502</p>
                {% endif %}
            </div>
            <div class="col">
                <h3>Фазы</h3>
                {% if s1 %}
                    <p>{{ s1 }}</p>
                {% else %}
                    <p>Ошибка на сервере 500/502</p>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

traffic_control/mainapp/templates/mainapp/req10.html
{% extends 'mainapp/base.html' %}
{% block content %}
    <h1>90460</h1>
    <div class="d-grid gap-2">
        <div class="row">
            <div class="col">
                <h3>Полная информация</h3>
                {% if jsons_full.time %}
                    <p>Time: {{ jsons_full.time }}</p>
                    <p>ID: {{ jsons_full.id }}</p>
                    <p>Created_AT: {{ jsons_full.rc_created_at }}</p>
                    <p>Updated_AT: {{ jsons_full.rc_updated_at }}</p>
                    <p>NUM_TL: {{ jsons_full.num_tl }}</p>
                    <p>is_Enabled: {{ jsons_full.is_enabled }}</p>
                    <p>is_Alarmed: {{ jsons_full.is_alarmed }}</p>
                    <p>type: {{ jsons_full.type }}</p>
                    <p>Protocol{{ jsons_full.protocol }}</p>
                    <p>CONN_STATUS: {{ jsons_full.conn_status }}</p>
                    <p>MODE: {{ jsons_full.mode }}</p>
                    <p>PROGRAM_ID:{{ jsons_full.program_id }}</p>
                    <p>KEEP_PHASE_ID: {{ jsons_full.keep_phase_id }}</p>
                    <p>Changed_time_at: {{ jsons_full.changed_time_at }}</p>
                    <p>Real_mode: {{ jsons_full.real_mode }}</p>
                    <p>Real_program_ID: {{ jsons_full.real_program_id }}</p>
                    <p>Real_keep_phase_id: {{ jsons_full.real_keep_phase_id }}</p>
                    <p>Program_created_at: {{ jsons_full.program_created_at }}</p>
                    <p>Program_updated_at{{ jsons_full.program_updated_at }}</p>
                    <p>T-Cycle: {{ jsons_full.t_cycle }}</p>
                    <p>Program_Type: {{ jsons_full.program_type }}</p>
                    <p>Start_phase_id: {{ jsons_full.start_phase_id }}</p>
                {% else %}
                    <p>Ошибка на сервере 500/502</p>
                {% endif %}
            </div>
            <div class="col">
                <h3>Статус</h3>
                {% if json %}
                    <p>{{ json }}</p>
                {% else %}
                    <p>Ошибка на сервере 500/502</p>
                {% endif %}
            </div>
            <div class="col">
                <h3>Фазы</h3>
                {% if s1 %}
                    <p>{{ s1 }}</p>
                {% else %}
                    <p>Ошибка на сервере 500/502</p>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

traffic_control/mainapp/templates/mainapp/req2.html
{% extends 'mainapp/base.html' %}
{% block content %}
    <h1>90452</h1>
    <div class="d-grid gap-2">
        <div class="row">
            <div class="col">
                <h3>Полная информация</h3>
                {% if jsons_full.time %}
                    <p>Time: {{ jsons_full.time }}</p>
                    <p>ID: {{ jsons_full.id }}</p>
                    <p>Created_AT: {{ jsons_full.rc_created_at }}</p>
                    <p>Updated_AT: {{ jsons_full.rc_updated_at }}</p>
                    <p>NUM_TL: {{ jsons_full.num_tl }}</p>
                    <p>is_Enabled: {{ jsons_full.is_enabled }}</p>
                    <p>is_Alarmed: {{ jsons_full.is_alarmed }}</p>
                    <p>type: {{ jsons_full.type }}</p>
                    <p>Protocol{{ jsons_full.protocol }}</p>
                    <p>CONN_STATUS: {{ jsons_full.conn_status }}</p>
                    <p>MODE: {{ jsons_full.mode }}</p>
                    <p>PROGRAM_ID:{{ jsons_full.program_id }}</p>
                    <p>KEEP_PHASE_ID: {{ jsons_full.keep_phase_id }}</p>
                    <p>Changed_time_at: {{ jsons_full.changed_time_at }}</p>
                    <p>Real_mode: {{ jsons_full.real_mode }}</p>
                    <p>Real_program_ID: {{ jsons_full.real_program_id }}</p>
                    <p>Real_keep_phase_id: {{ jsons_full.real_keep_phase_id }}</p>
                    <p>Program_created_at: {{ jsons_full.program_created_at }}</p>
                    <p>Program_updated_at{{ jsons_full.program_updated_at }}</p>
                    <p>T-Cycle: {{ jsons_full.t_cycle }}</p>
                    <p>Program_Type: {{ jsons_full.program_type }}</p>
                    <p>Start_phase_id: {{ jsons_full.start_phase_id }}</p>
                {% else %}
                    <p>Ошибка на сервере 500/502</p>
                {% endif %}
            </div>
            <div class="col">
                <h3>Статус</h3>
                {% if json %}
                    <p>{{ json }}</p>
                {% else %}
                    <p>Ошибка на сервере 500/502</p>
                {% endif %}
            </div>
            <div class="col">
                <h3>Фазы</h3>
                {% if s1 %}
                    <p>{{ s1 }}</p>
                {% else %}
                    <p>Ошибка на сервере 500/502</p>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

traffic_control/mainapp/templates/mainapp/req3.html
{% extends 'mainapp/base.html' %}
{% block content %}
    <h1>90453</h1>
    <div class="d-grid gap-2">
        <div class="row">
            <div class="col">
                <h3>Полная информация</h3>
                {% if jsons_full.time %}
                    <p>Time: {{ jsons_full.time }}</p>
                    <p>ID: {{ jsons_full.id }}</p>
                    <p>Created_AT: {{ jsons_full.rc_created_at }}</p>
                    <p>Updated_AT: {{ jsons_full.rc_updated_at }}</p>
                    <p>NUM_TL: {{ jsons_full.num_tl }}</p>
                    <p>is_Enabled: {{ jsons_full.is_enabled }}</p>
                    <p>is_Alarmed: {{ jsons_full.is_alarmed }}</p>
                    <p>type: {{ jsons_full.type }}</p>
                    <p>Protocol{{ jsons_full.protocol }}</p>
                    <p>CONN_STATUS: {{ jsons_full.conn_status }}</p>
                    <p>MODE: {{ jsons_full.mode }}</p>
                    <p>PROGRAM_ID:{{ jsons_full.program_id }}</p>
                    <p>KEEP_PHASE_ID: {{ jsons_full.keep_phase_id }}</p>
                    <p>Changed_time_at: {{ jsons_full.changed_time_at }}</p>
                    <p>Real_mode: {{ jsons_full.real_mode }}</p>
                    <p>Real_program_ID: {{ jsons_full.real_program_id }}</p>
                    <p>Real_keep_phase_id: {{ jsons_full.real_keep_phase_id }}</p>
                    <p>Program_created_at: {{ jsons_full.program_created_at }}</p>
                    <p>Program_updated_at{{ jsons_full.program_updated_at }}</p>
                    <p>T-Cycle: {{ jsons_full.t_cycle }}</p>
                    <p>Program_Type: {{ jsons_full.program_type }}</p>
                    <p>Start_phase_id: {{ jsons_full.start_phase_id }}</p>
                {% else %}
                    <p>Ошибка на сервере 500/502</p>
                {% endif %}
            </div>
            <div class="col">
                <h3>Статус</h3>
                {% if json %}
                    <p>{{ json }}</p>
                {% else %}
                    <p>Ошибка на сервере 500/502</p>
                {% endif %}
            </div>
            <div class="col">
                <h3>Фазы</h3>
                {% if s1 %}
                    <p>{{ s1 }}</p>
                {% else %}
                    <p>Ошибка на сервере 500/502</p>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}